var shuffleSequence = seq("intro", sepWith("sep",  seq("practice")), "practiceover", sepWith("sep", rshuffle(startsWith("first"), startsWith("filler"))));
var continueMessage = ["Klikni zde"];
var aj = "AcceptabilityJudgment";
var q = "Question";
var completionMessage = "[Zadané odpovědi jsou odeslány na server. Děkujeme za spolupráci!]";
var ms = "Message";

var defaults = [
    "Separator", {
        transfer: 800,
        normalMessage: "Počkejte prosím na další položku v experimentu.",
        errorMessage: "Špatně. Počkejte prosím na další položku v experimentu."
    },
    
    "AcceptabilityJudgment", {
        as: ["Ano", "Ne"],
        presentAsScale: false,
        presentHorizontally: true,
        leftComment: "(věta v kontextu odpovídá obrázku)",
        rightComment: "(věta v kontextu neodpovídá obrázku)",
        randomOrder: false,
        showNumbers: false,

    },
     "Message", { hideProgressBar: true, transfer: "click" }
];
var progressBarText = "";

var items = [["sep", "Separator", { }],  
["intro", "Form", {continueMessage: "Pro vstup do experimentu, klikněte zde", html: {include: "intro.html"}}],
  ["practice", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1jwSIA9yQkKB9fSKDWUPiNoQ4xdzxmCeY\"></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Pouze jeden z kluků nakrmil psa.</i></p></p>Věta je adekvátní vůči kontextu a zároveň odpovídá obrázku, neboť na něm pouze jeden kluk krmí psa. Odpověď <i>Ne</i> zde není adekvátní, protože obrázek se k větě hodí. Klikněte tedy na odpověď <i>Ano</i>.</center>"}, hasCorrect: 0}],
             
["practice", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:400px;max-height:400px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1W7D363fxA_X9KgIgOU6xkj9knEPzIPiz\"></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Milan viděl Áďu natáčet tři zvířata.</i></p></p>Věta je sice adekvátní vůči kontextu, ale obrázek dané větě neodpovídá, neboť na něm Áďa jedno ze zvířat krmí. Odpověď <i>Ano</i> zde není adekvátní, protože obrázek se k větě nehodí. Klikněte tedy na odpověď <i>Ne</i>.</center>"}, hasCorrect: 1}],
            
["practice", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:450px;max-height:450px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1W6lUPdpiS-tyPnlPtwkGpqHbx_Q7_1jm\"></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Obě holky nakrmili kozla.</i></p></p>Věta je adekvátní vůči kontextu a zároveň odpovídá obrázku. Zvolte možnost <i>Ano</i>.</center>"}, hasCorrect: 0}],             

          ["practiceover", "Message", {continueMessage: "Klikněte zde pro pokračování experimentu", html: ["div", ["p", "Zde končí přípravná část experimentu. Klikněte níže pro vstup do experimentu."]]}],

//NPobji
[["first-npobji-1a", 1], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1mje99eEtaXodN3Y7iNjsQnDlC4GfuTX9\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Klára a Šimon viděli Tínu natáčet velblouda i žirafu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npobji-1b", 1], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1a1cniEY_zwpwO9oxMWT-lxCkHqFY-OVc\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Klára a Šimon viděli Tínu natáčet velblouda i žirafu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npobji-1c", 1], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1PWdVAVKz7OYetf5OMTkHa71QZMndDp3O\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Klára a Šimon viděli Tínu natáčet velblouda i žirafu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

[["first-npobji-2a", 2], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1L2BdstL1AuS6_ceiCNm2pTkfxgCpOQxS\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Tína a Dan viděli Kláru krmit osla i prase.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npobji-2b", 2], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1t1KBQSfORtT7_h4zy7x6KhiCgwtaPaxr\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Tína a Dan viděli Kláru krmit osla i prase.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npobji-2c", 2], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=19cPGL5VYSfDsB-YVig_e4VqTaY2RQZd_\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Tína a Dan viděli Kláru krmit osla i prase.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

[["first-npobji-3a", 3], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1OfRCpDuAlWkVqY5Rw9xhkYNiZbjGLc50\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dan a Adam viděli Sáru fotit nosorožce i slona.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npobji-3b", 3], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1xgqppNaMg-pDPbeUld_gx-LmVbe0Yvju\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dan a Adam viděli Sáru fotit nosorožce i slona.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npobji-3c", 3], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1BDmx4IibQyQVaxV4X5wO8WJSUd98Kz1H\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dan a Adam viděli Sáru fotit nosorožce i slona.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

[["first-npobji-4a", 4], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1-iTjP0L9NUJEIstnrRnJfWB5CTbTf4GZ\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Áďa a Milan viděli Dana krmit kozla i ovci.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npobji-4b", 4], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1g1KjZa5uw3XI5Zh7iONIkqky-AAbj9NR\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Áďa a Milan viděli Dana krmit kozla i ovci.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npobji-4c", 4], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1SjTogndEQTFisOCVtxjIrXDA1lUY3_Pw\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Áďa a Milan viděli Dana krmit kozla i ovci.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

[["first-npobji-5a", 5], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1jnaOUjUOi23a9S5KIy7T-XL0fZVQgHwc\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Milan a Šimon viděli Áďu natáčet lva i tygra.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npobji-5b", 5], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1XjspJEgz4aHYiFQA2CD57Qmc3lRLbSVq\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Milan a Šimon viděli Áďu natáčet lva i tygra.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npobji-5c", 5], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1FpRMamL7U70qYVxnoFv_07f8ciZC5rgE\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Milan a Šimon viděli Áďu natáčet lva i tygra.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

[["first-npobji-6a", 6], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1zZvFQeqatt03WJEmDLCVTM5I70hd26Ju\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Šimon a Áďa viděli Milana krmit kočku i psa.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npobji-6b", 6], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1Cs-q_EtgMj6ZUW9RYoBhSwL3rLjKtQgu\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Šimon a Áďa viděli Milana krmit kočku i psa.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npobji-6c", 6], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1C0R7-8sSFi9ERh-KQEFN2uWLk_Ov9ixa\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Šimon a Áďa viděli Milana krmit kočku i psa.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

[["first-npobji-7a", 7], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1729qFUsZsmi1SopdYXZkOin4jOX_Y4hV\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Adam a Dan viděli Tínu fotit lamu i antilopu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npobji-7b", 7], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=10INcHpaB0iP1_GZQIIKskAoyRaQjJSVd\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Adam a Dan viděli Tínu fotit lamu i antilopu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npobji-7c", 7], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=16BhECNL8KWbfU1JOb-BJnoQ8hn6vNNks\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Adam a Dan viděli Tínu fotit lamu i antilopu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

[["first-npobji-8a", 8], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1WOksRncweJKFnblU2tWXwVxx4X9zm18l\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dan a Tína viděli Adama krmit slepici i husu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npobji-8b", 8], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=16FRCML6hI1nFATCmst6VvkbrDoCWc_J7\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dan a Tína viděli Adama krmit slepici i husu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npobji-8c", 8], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1S-uIgIa6WxA5slL12ks8ADKUv3F-468P\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dan a Tína viděli Adama krmit slepici i husu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

[["first-npobji-9a", 9], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1FekvTRL8PXM6u3i_3r-9cWe4zgKrqw93\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Šimon a Klára viděli Sáru krmit ovci i koně.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npobji-9b", 9], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1VaNlv_IeL1m6I1CnjeumH5gHHrsHRDvP\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Šimon a Klára viděli Sáru krmit ovci i koně.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npobji-9c", 9], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1lc64wll130zC_wArhgG7NdlDTqiU788P\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Šimon a Klára viděli Sáru krmit ovci i koně.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

//NPsubji
   
[["first-npsubji-1a", 10], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=15Er3pVzgCMNFJ7CxFHkcJ_gY87FayhOF\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Áďa i Milan viděli Tínu fotit velblouda a žirafu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npsubji-1b", 10], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1JGsBktnMOcWZXSWDRC5CLrHuTZTOrORn\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Áďa i Milan viděli Tínu fotit velblouda a žirafu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npsubji-1c", 10], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1InVzeTLpMuZd-v6AN8CLPA4dLm9ylXdr\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Áďa i Milan viděli Tínu fotit velblouda a žirafu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

[["first-npsubji-2a", 11], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1LP03QM99lLdymUzv6Zkln-dEVIuBFV5K\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Adam i Klára viděli Milana krmit osla a prase.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npsubji-2b", 11], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1BauOs_YQUIrKjQaolpC6YythjqIaGlzC\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Adam i Klára viděli Milana krmit osla a prase.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npsubji-2c", 11], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1FKb09Y--wHBOnYDChEaEGZ81xFTsMEl8\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Adam i Klára viděli Milana krmit osla a prase.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

[["first-npsubji-3a", 12], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1BMv6OWnJNPEgHrj4kLqwIFEyVwtSCv1G\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dan i Áďa viděli Tínu natáčet nosorožce a slona.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npsubji-3b", 12], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1ls-qZiSUDmnyLH3cf6FJuszMF2bVXPik\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dan i Áďa viděli Tínu natáčet nosorožce a slona.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npsubji-3c", 12], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1eTgQE4WeJpn-gL_FueLDxxgGwQCNyjuY\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dan i Áďa viděli Tínu natáčet nosorožce a slona.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

[["first-npsubji-4a", 13], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1zxCqT8bSIJIFTvX3fhpcWB7M3S-2Gne0\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Šimon i Adam viděli Milana krmit kozla a ovci.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npsubji-4b", 13], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=15Qx7flmbAmPKG6J-J7-cPhZX_WLPa_RZ\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Šimon i Adam viděli Milana krmit kozla a ovci.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npsubji-4c", 13], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1-O3FizzKXyQsA5QZ-UW8ox-iZC_nndUs\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Šimon i Adam viděli Milana krmit kozla a ovci.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

[["first-npsubji-5a", 14], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1-LSW4UtNw60CQR4qNyBFcXlXEqAMc9kv\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Sára i Dan viděli Áďu fotit lva a tygra.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npsubji-5b", 14], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1IRFDiTw23ge-3gln8QccyQxAZEroV_Gk\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Sára i Dan viděli Áďu fotit lva a tygra.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npsubji-5c", 14], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1OxfXLbrJIS80SCAREXFZHQTUMvJ9kx0Q\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Sára i Dan viděli Áďu fotit lva a tygra.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

[["first-npsubji-6a", 15], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1t8W7HK34nkVr2TE36hh1KT3U8mPmZU7P\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Milan i Šimon viděli Adama krmit kočku a psa.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npsubji-6b", 15], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1KxdmbfrMT7zGgZpQPP_hVRSW_8ho7Mz7\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Milan i Šimon viděli Adama krmit kočku a psa.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npsubji-6c", 15], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1-DX99nEX9MkjlvXBgHf4T135kUWXZVRB\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Milan i Šimon viděli Adama krmit kočku a psa.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

[["first-npsubji-7a", 16], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1nZ4R-zXHMAHlI7pdBQHFRd1peaLfzJ_a\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Klára i Milan viděli Dana natáčet lamu a antilopu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npsubji-7b", 16], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1qKQxry3ARe4b9bp9zZbvoqQOY-ugzHKU\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Klára i Milan viděli Dana natáčet lamu a antilopu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npsubji-7c", 16], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1U75PjrMV_7aV6BGiGFRJd9a3Kdvy1cpI\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Klára i Milan viděli Dana natáčet lamu a antilopu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

[["first-npsubji-8a", 17], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1PAbV6znWyaAJKYQFeTJji0PtJ6WNyyQ6\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Áďa i Klára viděly Šimona krmit slepici a husu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npsubji-8b", 17], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1UF5O-28IT0O7C7IZkDCPSlySh40mlgYQ\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Áďa i Klára viděly Šimona krmit slepici a husu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npsubji-8c", 17], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1_xwdhUIb5Ij4VMiQ17usUS1D2t6MuixJ\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Áďa i Klára viděly Šimona krmit slepici a husu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

[["first-npsubji-9a", 18], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1dTxxjUw0c7VDSF2MncOLv6XArmftZ9YP\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Adam i Klára viděli Tínu krmit ovci a koně.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npsubji-9b", 18], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1NZnQZIJ5QWRAwPfWe14dBTcMaS0CQou9\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Adam i Klára viděli Tínu krmit ovci a koně.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-npsubji-9c", 18], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1RxZNTtOoWc6EXg_mBdJ6C2hmEXhpcM8B\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Adam i Klára viděli Tínu krmit ovci a koně.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

//NumPobji

[["first-numpobji-1a", 19], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1ak67nr34to3lfFnpL7PVY-x6fdSsfAXR\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dvě holky viděly Sáru fotit velblouda i žirafu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpobji-1b", 19], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1xzHKtBb33qitl2JR29u5clzhu66g9ZXq\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dvě holky viděly Sáru fotit velblouda i žirafu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpobji-1c", 19], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1VHgfJ9kH9bxlhiz-sxCkDRtOe7yAmIQT\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dvě holky viděly Sáru fotit velblouda i žirafu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

[["first-numpobji-2a", 20], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1lHw1C_pFHHHshT1RUZIESE8T68PpmfAr\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dva kluci viděli Áďu krmit osla i prase.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpobji-2b", 20], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1opCnerLliv7cmWmxBkwpKg_jX_KhBu5W\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dva kluci viděli Áďu krmit osla i prase.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpobji-2c", 20], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1ttnwUYfqc6cTXdzDMDWhvU1skgfFMeHz\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dva kluci viděli Áďu krmit osla i prase.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

[["first-numpobji-3a", 21], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1aF8NhUn5o0tJ3B75p2J7NrSYgV80egzi\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dvě holky viděly Adama natáčet nosorožce i slona.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpobji-3b", 21], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1Rr9qbWPsmJi1SpuYTwZY8BUJbSULet18\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dvě holky viděly Adama natáčet nosorožce i slona.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpobji-3c", 21], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1aG29yOaIeLwlCk2mBNIyZ41Q_FxbVDwe\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dvě holky viděly Adama natáčet nosorožce i slona.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

[["first-numpobji-4a", 22], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1AjTFH7D_dt4R8rwZXqTjnAsVKNESb1DH\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dva kluci viděli Sáru krmit kozla i ovci.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpobji-4b", 22], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1yoczaxCuYnNrGw1I7QPDy9KQFYLOA41Z\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dva kluci viděli Sáru krmit kozla i ovci.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpobji-4c", 22], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1ZMd75oFu64KyJ-bwZRhMf4vJixNiNOOS\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dva kluci viděli Sáru krmit kozla i ovci.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

[["first-numpobji-5a", 23], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1z6Qr1GpPNyoYO3X3guoIinW_ZWhcjiU8\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dvě holky viděly Milana fotit lva i tygra.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpobji-5b", 23], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1Yn5_-hpr4AEvvarknkr6dLvCwImZKoOP\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dvě holky viděly Milana fotit lva i tygra.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpobji-5c", 23], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1kZCVLrwScCwMNsPhZARnykwWcZ2OG-Xq\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dvě holky viděly Milana fotit lva i tygra.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

[["first-numpobji-6a", 24], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1xK_sV3QUjJdoUOkyYL8SUla3sH4gN1Mk\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dva kluci viděli Kláru krmit kočku i psa.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpobji-6b", 24], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=10KCD_9de9R7JAgNLh4DXyysmmMXadxh5\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dva kluci viděli Kláru krmit kočku i psa.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpobji-6c", 24], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1rzDNeIUbgbzJD3YH9JBOGyfNgoHqOS1N\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dva kluci viděli Kláru krmit kočku i psa.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

[["first-numpobji-7a", 25], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1lDLNn5cetnutdb6bUbfh2l0nM19zh3IK\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dvě holky viděly Dana natáčet lamu i antilopu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpobji-7b", 25], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1NNkjLHFiBN0ujOgw8giwTg-Gcm-ccUQw\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dvě holky viděly Dana natáčet lamu i antilopu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpobji-7c", 25], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1mDRpXkhGVYtRSIQ81L_oa4ZZ1RUufMXn\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dvě holky viděly Dana natáčet lamu i antilopu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

[["first-numpobji-8a", 26], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1k9fDg2-rGNrCvG2lBeSlQj5lfxhSznDB\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dva kluci viděli Tínu krmit slepici i husu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpobji-8b", 26], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1ikXlxwVSq2oZwKfyJLtud5zzB_vN951J\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dva kluci viděli Tínu krmit slepici i husu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpobji-8c", 26], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1yKO2OOU0F_taoJlDGHltlLyNvH0shmDv\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dva kluci viděli Tínu krmit slepici i husu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

[["first-numpobji-9a", 27], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1kUhX9XzJZbaHPY-0kYHAhgb0h7YkQQbw\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dva kluci viděli Sáru krmit ovci i koně.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpobji-9b", 27], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1X7UWbZIqLR-1dhxqPBGeb4e1E57Wmpn3\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dva kluci viděli Sáru krmit ovci i koně.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpobji-9c", 27], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1NZBWeJrxFcI2_82W0_15oggsmoPGG3fv\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dva kluci viděli Sáru krmit ovci i koně.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

//Numsubji

[["first-numpsubji-1a", 28], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=161JgRUen4NORpji20_rCTaD2o3uW7Mf6\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Milan i Klára viděli Áďu fotit dvě zvířata.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpsubji-1b", 28], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1pW84QWZr8b9t9WGkYTDCNDPj7yjCNWgo\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Milan i Klára viděli Áďu fotit dvě zvířata.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpsubji-1c", 28], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1z57V6MzagD33LDPzngUOV35smp2hnMHo\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Milan i Klára viděli Áďu fotit dvě zvířata.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

[["first-numpsubji-2a", 29], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1ET4iiutoiIZp0_J7uu68d8q421LUDjgH\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Klára i Sára viděly Áďu krmit dvě zvířata.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpsubji-2b", 29], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=18SDvCtO_1C2-NGh7etof3jNn_W_9bXQs\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Klára i Sára viděly Áďu krmit dvě zvířata.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpsubji-2c", 29], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1P7nVmdODQm-1kU7ysQfgIAqrhRh2AvqN\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Klára i Sára viděly Áďu krmit dvě zvířata.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

[["first-numpsubji-3a", 30], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1THnEMjaFFFZN71BnjXrsMLYpuotEMHFW\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Tína i Šimon viděli Dana natáčet dvě zvířata.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpsubji-3b", 30], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1aHjvbKgrN5mKL8mZeIWl-za8zswyorGw\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Tína i Šimon viděli Dana natáčet dvě zvířata.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpsubji-3c", 30], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1t43oUF2TByKKugMR39M0oWfzpYwObIBK\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Tína i Šimon viděli Dana natáčet dvě zvířata.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

[["first-numpsubji-4a", 31], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1ebNnjRAr4yjHKu0YmOJDDs-KKPB3uKy8\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Šimon i Adam viděli Sáru krmit dvě zvířata.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpsubji-4b", 31], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=137sSGEdw1BgJkTkVzaVapaada-kq7k8g\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Šimon i Adam viděli Sáru krmit dvě zvířata.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpsubji-4c", 31], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1171hPHoI_dC0DSfxWR25UjxOMoBgAZv4\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Šimon i Adam viděli Sáru krmit dvě zvířata.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

[["first-numpsubji-5a", 32], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1vjUTajkF2X9uTITV1OavJB4wdYCVE0if\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Adam i Dan viděli Šimona fotit dvě zvířata.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpsubji-5b", 32], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1DECXITbWkdsjbWeEHk5slwmTFQ26zk3l\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Adam i Dan viděli Šimona fotit dvě zvířata.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpsubji-5c", 32], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1xJNKveRJnyvLbTOBAYcXnJ77UmEfujmE\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Adam i Dan viděli Šimona fotit dvě zvířata.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

[["first-numpsubji-6a", 33], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=15c3TcOZ3g8qtSIshvdIr-6fpVjvuIOpr\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dan i Áďa viděli Kláru krmit dvě zvířata.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpsubji-6b", 33], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1VTJeHG4SkU4Am0D18bwfpemH_pgEMTKf\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dan i Áďa viděli Kláru krmit dvě zvířata.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpsubji-6c", 33], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1muPuTGpBYa1UFBJ9jYG2Gh6MY6spGsOQ\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dan i Áďa viděli Kláru krmit dvě zvířata.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

[["first-numpsubji-7a", 34], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=16OHO5tmJy_96KwfBUXfQvoYf8LqABukx\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Áďa i Milan viděli Šimona natáčet dvě zvířata.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpsubji-7b", 34], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1N0BsUuev_fcZZlBWkgliLzG7vty5rlsb\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Áďa i Milan viděli Šimona natáčet dvě zvířata.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpsubji-7c", 34], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=16q31dcwM8b8Qq9IcRNaC6biFu9r0jAg6\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Áďa i Milan viděli Šimona natáčet dvě zvířata.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

[["first-numpsubji-8a", 35], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1D3PJnqarsAgude1zz9AVFh63D50Oi5g1\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Milan i Klára viděli Adama krmit dvě zvířata.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpsubji-8b", 35], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1WpmsSsCCP_0HxJ17oTc83VfN_MfvQV6_\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Milan i Klára viděli Adama krmit dvě zvířata.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpsubji-8c", 35], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1wwPmZmiXNPVEb-Rbv8S0jEqrIdUFwXEm\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Milan i Klára viděli Adama krmit dvě zvířata.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

[["first-numpsubji-9a", 36], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1_Sm_HWFboZRGvGBW1GdQqKUxGOGzk5gl\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Klára i Adam viděli Tínu krmit dvě zvířata.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpsubji-9b", 36], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1xIPgha9jz-9wsKi6gtpg4oP3PvMrvixS\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Klára i Adam viděli Tínu krmit dvě zvířata.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
[["first-numpsubji-9c", 36], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1aEQnzjwYUhnlaEiDRAc7Zf2hHePrW423\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Klára i Adam viděli Tínu krmit dvě zvířata.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

//Fillers

["filler-1b", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1oeN6u9HQ-n4UkhXRUzUPnMY-Z8R9ZzJZ\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Každá holka vyfotila obě zvířata.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
["filler-1g", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1LCOO4w2lpMcid_nKokSck_KJyO-ZOkd2\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Každá holka vyfotila obě zvířata.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
["filler-2b", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1IBHMNhoz2A5_uUn9HZyDbufrlJPmdpho\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Pouze jeden kluk nakrmil jednu husu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
["filler-2g", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1-DvIL3uz_PkJD9Nm2lnVhRXSVD_rZriw\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Pouze jeden kluk nakrmil jednu husu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
["filler-3b", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1oBNt7ViMmKpNgy96ntCh882oJC2oj7cf\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dva žáci vyfotili každý dva lvy.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
["filler-3g", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=14kDWEvV7_jB9xA6BA0X0a4wXG9RFoO32\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dva žáci vyfotili každý dva lvy.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
["filler-4b", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=199i1iuQV8Cg3dq68sXPFEN-g2QPQUrhx\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Pouze jeden žák natočil obě ovce.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
["filler-4g", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1keUshaqcz_bMhPUJBDS9JTNA7dNwEgbx\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Pouze jeden žák natočil obě ovce.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
["filler-5b", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1fo3KNSWb1Qkt3xq_AYl2EnAMDaukcpUN\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Každý kluk stih nakrmit oba kozly.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
["filler-5g", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1_3Bu4BeRyTlNFOEqRvUC7Hvs9nI63uF8\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Každý kluk stih nakrmit oba kozly.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
["filler-6b", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1qgtzZr-HQ8O5iuIgVfn90yovbxV5Jz8s\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Pouze jedna holka vyfotila lamu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
["filler-6g", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1XI5-MVQw2DvnqioZSHkf9p4FRuGek6LZ\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Pouze jedna holka vyfotila lamu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
["filler-7b", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1Ko92xNyY7QGuRAYo6fgsRDo3giCRyMNL\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dvě holky nakrmily každá dvě prasata.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
["filler-7g", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1vFI_JrtrW6y37_N8B-FQvJhvyjc1G3lZ\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dvě holky nakrmily každá dvě prasata.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
["filler-8b", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1_NPFmkpNWQRqCEXkBEuNwQzd0_QP2RGj\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Pouze jeden žák natočil jednu žirafu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
["filler-8g", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1bJwq07cTttuRtsaztl4FLarFwLUHfdCk\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Pouze jeden žák natočil jednu žirafu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
["filler-9b", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1j9nKEyWDrk8ZcwtU6NO3r-QIxM9NZ0DW\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Každý kluk nakrmil dvě slepice.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
["filler-9g", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1y2-F74L072w_gRNgxpf7YKrI2S3mST2J\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Každý kluk nakrmil dvě slepice.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
["filler-10b", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1MOUwBhw2wGGLZEbu04VmfFs52sbSSPq8\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Každá holka nakrmila jedno zvíře.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
["filler-10g", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1Xvc1GczDtznIIpJ7O3VQfyD3q4X6p9dF\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Každá holka nakrmila jedno zvíře.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
["filler-11b", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1JBg1TbXYj1UsYDeYa5836DHFkocubuR2\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Pouze jeden kluk vyfotil kočku.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
["filler-11g", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1miN21QnmwmgohscUOgZfOvMzcDJqY4LC\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Pouze jeden kluk vyfotil kočku.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
["filler-12b", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=12Xjz0XCqykECpCbmXw_2TxyRKPQTZugg\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dva kluci natočili dvě husy.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
["filler-12g", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1ulH_fmzn38heBXZHkpHnjSIcVqgQ5avY\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dva kluci natočili dvě husy.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
["filler-13b", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1oRVNQlPpj2ruEKcwJrN6z-dE8yggq5LA\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dva žáci natočili dva lvy.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
["filler-13g", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1yKv21WPGgNXa2SZ4HIQGz5nnzJLTwpFY\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dva žáci natočili dva lvy.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
["filler-14b", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1bU1lUqI-5RUGUuRdxcBc48cY16uul0CT\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Holka vyfotila jednu husu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
["filler-14g", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1zV5G0DKD8jmcFIsLAMyX0OdO3PQGgATj\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Holka vyfotila jednu husu.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
["filler-15b", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=18fNmwlOrPRZF_Ju9izsh9H5tVyKRFiVQ\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Pouze kluk nakrmil slepici.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
["filler-15g", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1LoZNrSBDMS8qFtfLKifYgVjj9U76mchO\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Pouze kluk nakrmil slepici.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
["filler-16b", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1PlJfKgB_kF7OS7lZKAjk9yZ25nhanw9q\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dvě holky vyfotily každá dva slony.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],
["filler-16g", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:350px;max-height:350px;width: auto;height: auto;\" src=\"https://drive.google.com/uc?id=1mM6jbaGvKZ1bSRrpQnkehCQcQgqU78QO\"></td></table></center>Kontext: Pátá třída základní školy byla na výletě ve městské zoologické zahradě. Tam se děti mohli na zvířátka nejen dívat, ale některé dokonce nakrmit.</p><center><p>Věta: <i>Dvě holky vyfotily každá dva slony.</i></p></p>Odpovídá větě v daném kontextu tenhle obrázek?:</center>"}}],

];

